### ISSUE TITLE
Potential MITM attack

### ISSUE THREAD

**Issue by s1155016069** [ierg4210/shop60#1]
1.Detailed steps to reproduce? (e.g., visit /admin2 without login)
visit shop60 using http
2. What did you see? (e.g., led to a page that can delete a product)
it doesn't redirect to https
3. What did you expect to see? (e.g., admin actions require authentication)
it will redirect to https
4. What is the possible fix? (e.g., delete the sample/testing page)
redirect to https to avoid MITM attack

![store60](https://cloud.githubusercontent.com/assets/10684896/7510349/a16dbdbc-f4cd-11e4-9dbc-f8aaacd99161.png)

**Comment by sueger** [comment]
Sorry for late reply and deploy. Solved, thank you.

**Comment by zhusz** [comment]
Valid hacking.
